
#include "tigr.h"

#include "tigr_internal.h"
#include "tigr_upscale_gl_vs.h"
#include "tigr_upscale_gl_fs.h"

#include "tigr_bitmaps.c"
#include "tigr_loadpng.c"
#include "tigr_savepng.c"
#include "tigr_inflate.c"
#include "tigr_print.c"
#include "tigr_win.c"
#include "tigr_osx.c"
#include "tigr_ios.c"
#include "tigr_android.h"
#include "tigr_linux.c"
#include "tigr_android.c"
#include "tigr_gl.c"
#include "tigr_utils.c"